### ISSUE TITLE
Hi! can you make read-paf available using conda?

### ISSUE THREAD

**Issue by nettanetta** [alexomics/read-paf#9]
Hi!
I love your parser and use it in my research :)
Is it possible to make it available via conda also and not just using pip?
thanks!
Netta

**Comment by alexomics** [comment]
Hi Netta

I can take a look at this for you. 

In the meantime when you create a `conda` environment you can use `pip` to carry out the installation by specifying the environment YAML like so:

```yaml
name: readpaf_test
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - readpaf
```
